let prompty = prompt("Type something")
let confirmBox = confirm("You get another chance to type something")
let prompty2 = prompt("Type something again")
alert("Your input: " + prompty2)
console.log(prompty2)